CACHE MANIFEST
CACHE:
img/team-01.png
img/team-02.png
img/team-03.png
img/team-04.png
img/team-05.png
img/team-06.png
img/h1-bg.png
img/l1.jpg
img/keyboard-bg.jpg
img/iphone-bg.png
img/hero-bg.jpg
img/plants-bg.jpg
img/portfolio-01.jpg
img/portfolio-02.jpg
img/portfolio-03.jpg
img/portfolio-04.jpg
img/portfolio-05.jpg
img/portfolio-06.jpg
css/animate.css
css/bootstrap.min.css
css/flexslider.css
css/queries.css
css/styles.css
js/angular.js
js/bootstrap.min.js
js/invoice.js
js/jquery-1.11.1.min.js
js/jquery.flexslider.js
js/modernizr.js
js/scripts.js
js/waypoints.min.js
NETWORK:
*